### ISSUE TITLE
Upper bound for orientation check for bogus images

### ISSUE THREAD

**Issue by daneren2005** [willwashburn/FasterImage#10]
I have a image that is EXIF orientation 49.  That is obviously an invalid value, and the image itself has the correct dimensions otherwise.  It should report it as not rotated, but is reporting it as rotated.  I think https://github.com/willwashburn/fasterimage/blob/master/src/FasterImage/ExifParser.php#L74 should be changed from `return (! empty($this->orientation) && $this->orientation >= 5);` to `return (! empty($this->orientation) && $this->orientation >= 5 && $this->orientation <= 8);` to better handle all of the bogus images out there.

**Comment by daneren2005** [comment]
I did a super simple patch for it in my own branch: https://github.com/daneren2005/fasterimage.  I didn't create a PR because there are no tests and I edited the composer.json so I can use it through Packist.

**Comment by willwashburn** [comment]
Yeah, that change totally makes sense -- thanks @daneren2005!

I'm happy to write a test if you send me the image in question (if that's possible)

Also, you may already know this but just in case: you don't need to add the package to packagist / change the composer.json to use your fork in whatever project you included it in. Just add a section in your composer.json that looks like this:
```
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/daneren2005/fasterimage"
        }
    ],
```

From:
https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository


Anyways, thanks for the help! If you want to make a PR either way I'd be happy to merge it (without the composer.json changes, of course!)

**Comment by daneren2005** [comment]
Oh dang I didn't realize that.  That method would have been easier.  And no I cannot share the image because it is a private customer's image.

**Comment by daneren2005** [comment]
I created a simple PR with just this change and no tests: https://github.com/willwashburn/fasterimage/pull/11

**Comment by willwashburn** [comment]
Nice! Thanks!
