### ISSUE TITLE
Fallback support when curl_multi_init() is not available

### ISSUE THREAD

**Issue by westonruter** [willwashburn/FasterImage#16]
It turns out that even when cURL is installed, the `curl_multi_init()` function may be disabled on some hosts who are seeking to guard against DDoS attacks. See https://github.com/ampproject/amp-wp/pull/2183#issuecomment-491506514. 

Would it be feasible to check if this function exists in `FasterImage::batch()`, and if not, fallback to doing plain `curl_init()` calls to obtain the images sequentially?

**Comment by willwashburn** [comment]
I see -- interesting problem. Seems like thats a possibility and thats a reasonable solution although it would have a big performance impact.

Not sure when I'd have time to work on that in the coming weeks, but definitely open to making it a possibility eventually! 

Thanks again for the help on this, really appreciate it!

**Comment by westonruter** [comment]
Ok great. I'll work on a PR to implement, as long as you merge it 😊
