### ISSUE TITLE
Add support for SVG images

### ISSUE THREAD

**Issue by willwashburn** [willwashburn/FasterImage#5]

**Comment by JonasGroeger** [comment]
How would that even work? AFAIK, SVG files don't have height and width but rather instructions how to draw an image.

**Comment by willwashburn** [comment]
True -- I guess I just mean the height and width listed on the viewbox in the SVG. It's useful to know the aspect ratio. It's true that you could scale it to be larger / smaller as it is just instructions like you say

**Comment by willwashburn** [comment]
Fixed by #14
