### ISSUE TITLE
Exif parsing fails for image

### ISSUE THREAD

**Issue by willwashburn** [willwashburn/FasterImage#6]
http://gluesticksgumdrops.com/wp-content/uploads/2015/03/how-to-find-more-time-to-read-to-your-kids.jpg

Could not be parsed for some reason. Something isn't right in the exif parsing. The byte order is showing up as `*` here: https://github.com/willwashburn/FasterImage/blob/master/src/FasterImage/ExifParser.php#L80

**Comment by Yeshwanthyk** [comment]
Some more URLs that aren't working correctly with the exif parser:

http://bookporn.tumblr.com/post/124270956067 (http://40.media.tumblr.com/12e80446df6984d9107b2055e832841c/tumblr_nr80dtCqBE1ux7h8ko1_1280.jpg)

(I'll keep updating this list as I keep coming across outliers)

**Comment by willwashburn** [comment]
@Yeshwanthyk Looks like I was able to figure this out in b52f1a8. If the exif data is corrupt, we just ignore it and get the size anyway. It might mean some images with bad/corrupt exif data aren't the right orientation but.. cross that bridge when we get to it
